export declare let node_ps1_dotnetGetter: (() => any) | null;
export declare function setNodePs1Dotnet(fn: () => any): void;
export declare function getNodePs1Dotnet(): any;
export declare const callbackRegistry: Map<string, Function>;
export declare const typeMetadataCache: Map<string, Map<string, string>>;
export declare const globalTypeCache: Map<string, Map<string, string>>;
export declare const pendingInspectRequests: Map<string, string[]>;
export declare const pendingInspectTimeout: Map<string, NodeJS.Timeout>;
export declare const typeNameCache: Map<string, string>;
export declare const LARGE_ARRAY_THRESHOLD = 50;
export declare function getObjectTypeName(id: string): string | null;
export declare function getTypeMembers(typeName: string, memberNames: string[]): Map<string, string> | null;
export declare function ensureMemberTypeCached(id: string, memberName: string, memberCache: Map<string, string>): void;
export declare function createLazyArray(arr: any[]): any;
export declare function createProxyWithInlineProps(meta: any): any;
export declare function createProxy(meta: any): any;
